version: "3"

services:
  app:
    build:
      context: .  # sets the context to the current directory
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
      # the "-c" flag means "run a shell command"
      # "0.0.0.0" means django development server available on all ip addresses that run on the docker container
    environment:
      - DB_HOST=db  # needs to be the name of the db service below
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=mysupersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    # for production, you add an encrypted environment variables on your build server
    # that override these
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysupersecretpassword # most people don't user a password when developing locally
