name: Build, Lint, and Test App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run lint checker
        run: docker-compose run app sh -c "flake8"

      - name: Run Tests
        run: docker-compose run app sh -c "python manage.py test"
